server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${sky.datasource.driver-class-name}
      url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${sky.datasource.username}
      password: ${sky.datasource.password}
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.mis.backend.entity
  type-handlers-package: com.baomidou.mybatisplus.extension.handlers
  global-config:
    db-config:
      id-type: auto
      update-strategy: not_null
      insert-strategy: not_null
      where-strategy: not_null
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler



logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

sky:
  jwt:
    secret-key: aer
    ttl: 7200000
    token-name: token
